name: Build RENA Optimizer

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: dotnet build --configuration Release
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: RENA-Optimizer
          path: bin/Release/net8.0-windows/
