name: Build RENA Optimizer

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build Application
        run: dotnet build --configuration Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RENA-Optimizer-Package
          path: bin/Release/net8.0-windows/
